#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#------------------------------------------------------------------------------
# Allclean: remove the mesh, solution times, post-processing and processor
# directories, then restore the ParaView marker file (test.foam).
# Run before ./Allmesh to start from a pristine case.
#------------------------------------------------------------------------------

cleanCase
touch test.foam

#------------------------------------------------------------------------------
