#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#------------------------------------------------------------------------------
# rerun: re-run the decomposed parallel simulation without rebuilding the mesh.
#
# Use after changing flow parameters that do not affect the mesh layout
# (e.g. constant/Ubar.H or the target mean velocity). Re-decomposes with
# -force and reconstructs only the newly created time directories.
#------------------------------------------------------------------------------

runApplication -append decomposePar -force
runParallel -append simpleFoam
runApplication -append reconstructPar -newTimes

#------------------------------------------------------------------------------
