#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
./makeMesh

#runApplication mapFields ../channel_flow_simpleFoam/ -sourceTime 'latestTime' -consistent
runApplication decomposePar 
#runParallel snappyHexMesh -overwrite
#mpirun -np 4 snappyHexMesh -parallel -overwrite
#runApplication reconstructParMesh -mergeTol 1e-6
#runParallel renumberMesh -overwrite

#runParallel potentialFoam -initialiseUBCs

runParallel -append simpleFoam
runApplication -append reconstructPar -latestTime
rm processor* -r
runApplication -append postProcess -func sampleLines -latestTime
#------------------------------------------------------------------------------
