#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
./Allclean
rm 0 -r
cp 0_org 0 -r
cp constant/momentumTransport.kOmegaSST constant/momentumTransport
#cp constant/momentumTransport.dynamic* constant/momentumTransport
#rm  constant/triSurface/LF*

#cp /home/yux116/OpenFOAM/yux116-8/run/LFortunei/STLs/newSTLs/density_6_STL/fall_Adensity_6.stl constant/triSurface/LFs.stl

#surfaceTransformPoints -scale "(1 0.99 1)" constant/triSurface/LFs.stl constant/triSurface/LFs.stl
#surfaceTransformPoints -translate "(0.3 0 0)" constant/triSurface/LFs.stl constant/triSurface/LFs0.stl

#cat constant/triSurface/LFs1.stl >> constant/triSurface/LFs0.stl
#rm constant/triSurface/LFs1.stl
#runApplication -append blockMesh -dict system/blockMeshDict.bak
#writeMeshObj -patchFaces
#cp patchFaces_bottom_0.obj constant/triSurface/bottom.obj
#rm patchFaces*obj
runApplication -append blockMesh
#runApplication snappyHexMesh -overwrite
#runApplication decomposePar -copyZero
#runParallel snappyHexMesh -overwrite
#runApplication reconstructParMesh -constant -mergeTol 1e-6
#runApplication mapFields ../plane_2/ -sourceTime 'latestTime'
#runApplication createPatch -overwrite
#runApplication -append topoSet -dict system/topoSetDict
#runApplication -append refineMesh -overwrite
#runApplication -append topoSet -dict system/topoSetDict1
#runApplication -append refineMesh -overwrite
#runApplication -append topoSet -dict system/topoSetDict2
#runApplication -append refineMesh -overwrite
#runApplication -append refineWallLayer "(bottom)" 0.3 -overwrite
#runApplication -append refineWallLayer "(bottom)" 0.3 -overwrite
#runApplication -append refineWallLayer "(bottom)" 0.3 -overwrite

#------------------------------------------------------------------------------
